const chaiClasses = {
  // BACKGROUND COLORS
  "chai-bg-red": { type: "backgroundColor", value: "red" },
  "chai-bg-blue": { type: "backgroundColor", value: "blue" },
  "chai-bg-green": { type: "backgroundColor", value: "green" },
  "chai-bg-yellow": { type: "backgroundColor", value: "yellow" },
  "chai-bg-purple": { type: "backgroundColor", value: "purple" },
  "chai-bg-pink": { type: "backgroundColor", value: "pink" },
  "chai-bg-orange": { type: "backgroundColor", value: "orange" },
  "chai-bg-black": { type: "backgroundColor", value: "black" },
  "chai-bg-white": { type: "backgroundColor", value: "white" },
  "chai-bg-gray": { type: "backgroundColor", value: "gray" },
  "chai-bg-teal": { type: "backgroundColor", value: "teal" },
  "chai-bg-indigo": { type: "backgroundColor", value: "indigo" },

  // TEXT COLORS
  "chai-text-red": { type: "color", value: "red" },
  "chai-text-blue": { type: "color", value: "blue" },
  "chai-text-green": { type: "color", value: "green" },
  "chai-text-yellow": { type: "color", value: "yellow" },
  "chai-text-purple": { type: "color", value: "purple" },
  "chai-text-pink": { type: "color", value: "pink" },
  "chai-text-orange": { type: "color", value: "orange" },
  "chai-text-black": { type: "color", value: "black" },
  "chai-text-white": { type: "color", value: "white" },
  "chai-text-gray": { type: "color", value: "gray" },
  "chai-text-indigo": { type: "color", value: "indigo" },

  // FONT SIZE
  "chai-text-xs": { type: "fontSize", value: "12px" },
  "chai-text-sm": { type: "fontSize", value: "14px" },
  "chai-text-md": { type: "fontSize", value: "16px" },
  "chai-text-lg": { type: "fontSize", value: "20px" },
  "chai-text-xl": { type: "fontSize", value: "24px" },
  "chai-text-2xl": { type: "fontSize", value: "30px" },
  "chai-text-3xl": { type: "fontSize", value: "36px" },

  // TEXT ALIGN
  "chai-text-left": { type: "textAlign", value: "left" },
  "chai-text-center": { type: "textAlign", value: "center" },
  "chai-text-right": { type: "textAlign", value: "right" },

  // FONT WEIGHT
  "chai-font-light": { type: "fontWeight", value: "300" },
  "chai-font-normal": { type: "fontWeight", value: "400" },
  "chai-font-medium": { type: "fontWeight", value: "500" },
  "chai-font-semibold": { type: "fontWeight", value: "600" },
  "chai-font-bold": { type: "fontWeight", value: "700" },

  // DISPLAY
  "chai-block": { type: "display", value: "block" },
  "chai-inline": { type: "display", value: "inline" },
  "chai-inline-block": { type: "display", value: "inline-block" },
  "chai-flex": { type: "display", value: "flex" },
  "chai-grid": { type: "display", value: "grid" },
  "chai-hidden": { type: "display", value: "none" },

  // FLEX JUSTIFY
  "chai-justify-start": { type: "justifyContent", value: "flex-start" },
  "chai-justify-center": { type: "justifyContent", value: "center" },
  "chai-justify-end": { type: "justifyContent", value: "flex-end" },
  "chai-justify-between": { type: "justifyContent", value: "space-between" },
  "chai-justify-around": { type: "justifyContent", value: "space-around" },

  // FLEX ALIGN
  "chai-items-start": { type: "alignItems", value: "flex-start" },
  "chai-items-center": { type: "alignItems", value: "center" },
  "chai-items-end": { type: "alignItems", value: "flex-end" },
  "chai-items-stretch": { type: "alignItems", value: "stretch" },
  "chai-items-baseline": { type: "alignItems", value: "baseline" },

  // FLEX DIRECTION / WRAP
  "chai-flex-row": { type: "flexDirection", value: "row" },
  "chai-flex-col": { type: "flexDirection", value: "column" },
  "chai-flex-wrap": { type: "flexWrap", value: "wrap" },
  "chai-flex-nowrap": { type: "flexWrap", value: "nowrap" },

  // BORDER
  "chai-border": { type: "border", value: "1px solid black" },
  "chai-border-2": { type: "border", value: "2px solid black" },
  "chai-border-4": { type: "border", value: "4px solid black" },
  "chai-border-none": { type: "border", value: "none" },

  // BORDER RADIUS
  "chai-rounded-none": { type: "borderRadius", value: "0" },
  "chai-rounded-sm": { type: "borderRadius", value: "4px" },
  "chai-rounded-md": { type: "borderRadius", value: "8px" },
  "chai-rounded-lg": { type: "borderRadius", value: "16px" },
  "chai-rounded-xl": { type: "borderRadius", value: "24px" },
  "chai-rounded-full": { type: "borderRadius", value: "9999px" },

  // BORDER COLORS
  "chai-border-red": { type: "borderColor", value: "red" },
  "chai-border-blue": { type: "borderColor", value: "blue" },
  "chai-border-green": { type: "borderColor", value: "green" },
  "chai-border-yellow": { type: "borderColor", value: "yellow" },
  "chai-border-purple": { type: "borderColor", value: "purple" },
  "chai-border-pink": { type: "borderColor", value: "pink" },
  "chai-border-orange": { type: "borderColor", value: "orange" },
  "chai-border-black": { type: "borderColor", value: "black" },
  "chai-border-white": { type: "borderColor", value: "white" },
  "chai-border-gray": { type: "borderColor", value: "gray" },
  "chai-border-teal": { type: "borderColor", value: "teal" },
  "chai-border-indigo": { type: "borderColor", value: "indigo" },
  "chai-border-lime": { type: "borderColor", value: "lime" },
  "chai-border-cyan": { type: "borderColor", value: "cyan" },
  "chai-border-brown": { type: "borderColor", value: "brown" },

  // WIDTH
  "chai-w-auto": { type: "width", value: "auto" },
  "chai-w-25": { type: "width", value: "25%" },
  "chai-w-50": { type: "width", value: "50%" },
  "chai-w-75": { type: "width", value: "75%" },
  "chai-w-100": { type: "width", value: "100%" },
  "chai-w-screen": { type: "width", value: "100vw" },

  // HEIGHT
  "chai-h-auto": { type: "height", value: "auto" },
  "chai-h-25": { type: "height", value: "25%" },
  "chai-h-50": { type: "height", value: "50%" },
  "chai-h-75": { type: "height", value: "75%" },
  "chai-h-100": { type: "height", value: "100%" },
  "chai-h-screen": { type: "height", value: "100vh" },

  // CURSOR
  "chai-cursor-pointer": { type: "cursor", value: "pointer" },
  "chai-cursor-default": { type: "cursor", value: "default" },

  // OVERFLOW
  "chai-overflow-hidden": { type: "overflow", value: "hidden" },
  "chai-overflow-scroll": { type: "overflow", value: "scroll" },
  "chai-overflow-auto": { type: "overflow", value: "auto" },

  // POSITION
  "chai-relative": { type: "position", value: "relative" },
  "chai-absolute": { type: "position", value: "absolute" },
  "chai-fixed": { type: "position", value: "fixed" },

  // INSET
  "chai-top-0": { type: "top", value: "0" },
  "chai-right-0": { type: "right", value: "0" },
  "chai-bottom-0": { type: "bottom", value: "0" },
  "chai-left-0": { type: "left", value: "0" },
  "chai-inset-0": { type: "inset", value: "0" },

  // Z-INDEX
  "chai-z-0": { type: "zIndex", value: "0" },
  "chai-z-10": { type: "zIndex", value: "10" },
  "chai-z-20": { type: "zIndex", value: "20" },
  "chai-z-50": { type: "zIndex", value: "50" },

  // PADDING
  "chai-p-0": { type: "padding", value: "0px" },
  "chai-p-2": { type: "padding", value: "2px" },
  "chai-p-4": { type: "padding", value: "4px" },
  "chai-p-6": { type: "padding", value: "6px" },
  "chai-p-8": { type: "padding", value: "8px" },
  "chai-p-10": { type: "padding", value: "10px" },
  "chai-p-12": { type: "padding", value: "12px" },
  "chai-p-14": { type: "padding", value: "14px" },
  "chai-p-16": { type: "padding", value: "16px" },
  "chai-p-20": { type: "padding", value: "20px" },
  "chai-p-24": { type: "padding", value: "24px" },
  "chai-p-32": { type: "padding", value: "32px" },

  // PADDING X
  "chai-px-0": { type: "paddingInline", value: "0px" },
  "chai-px-2": { type: "paddingInline", value: "2px" },
  "chai-px-4": { type: "paddingInline", value: "4px" },
  "chai-px-6": { type: "paddingInline", value: "6px" },
  "chai-px-8": { type: "paddingInline", value: "8px" },
  "chai-px-10": { type: "paddingInline", value: "10px" },
  "chai-px-12": { type: "paddingInline", value: "12px" },
  "chai-px-14": { type: "paddingInline", value: "14px" },
  "chai-px-16": { type: "paddingInline", value: "16px" },
  "chai-px-20": { type: "paddingInline", value: "20px" },
  "chai-px-24": { type: "paddingInline", value: "24px" },
  "chai-px-32": { type: "paddingInline", value: "32px" },

  // PADDING Y
  "chai-py-0": { type: "paddingBlock", value: "0px" },
  "chai-py-2": { type: "paddingBlock", value: "2px" },
  "chai-py-4": { type: "paddingBlock", value: "4px" },
  "chai-py-6": { type: "paddingBlock", value: "6px" },
  "chai-py-8": { type: "paddingBlock", value: "8px" },
  "chai-py-10": { type: "paddingBlock", value: "10px" },
  "chai-py-12": { type: "paddingBlock", value: "12px" },
  "chai-py-14": { type: "paddingBlock", value: "14px" },
  "chai-py-16": { type: "paddingBlock", value: "16px" },
  "chai-py-20": { type: "paddingBlock", value: "20px" },
  "chai-py-24": { type: "paddingBlock", value: "24px" },
  "chai-py-32": { type: "paddingBlock", value: "32px" },

  // PADDING SIDES
  "chai-pt-0": { type: "paddingTop", value: "0px" },
  "chai-pt-2": { type: "paddingTop", value: "2px" },
  "chai-pt-4": { type: "paddingTop", value: "4px" },
  "chai-pt-6": { type: "paddingTop", value: "6px" },
  "chai-pt-8": { type: "paddingTop", value: "8px" },
  "chai-pt-10": { type: "paddingTop", value: "10px" },
  "chai-pt-12": { type: "paddingTop", value: "12px" },
  "chai-pt-14": { type: "paddingTop", value: "14px" },
  "chai-pt-16": { type: "paddingTop", value: "16px" },
  "chai-pt-20": { type: "paddingTop", value: "20px" },
  "chai-pt-24": { type: "paddingTop", value: "24px" },
  "chai-pt-32": { type: "paddingTop", value: "32px" },
  "chai-pr-0": { type: "paddingRight", value: "0px" },
  "chai-pr-2": { type: "paddingRight", value: "2px" },
  "chai-pr-4": { type: "paddingRight", value: "4px" },
  "chai-pr-6": { type: "paddingRight", value: "6px" },
  "chai-pr-8": { type: "paddingRight", value: "8px" },
  "chai-pr-10": { type: "paddingRight", value: "10px" },
  "chai-pr-12": { type: "paddingRight", value: "12px" },
  "chai-pr-14": { type: "paddingRight", value: "14px" },
  "chai-pr-16": { type: "paddingRight", value: "16px" },
  "chai-pr-20": { type: "paddingRight", value: "20px" },
  "chai-pr-24": { type: "paddingRight", value: "24px" },
  "chai-pr-32": { type: "paddingRight", value: "32px" },
  "chai-pb-0": { type: "paddingBottom", value: "0px" },
  "chai-pb-2": { type: "paddingBottom", value: "2px" },
  "chai-pb-4": { type: "paddingBottom", value: "4px" },
  "chai-pb-6": { type: "paddingBottom", value: "6px" },
  "chai-pb-8": { type: "paddingBottom", value: "8px" },
  "chai-pb-10": { type: "paddingBottom", value: "10px" },
  "chai-pb-12": { type: "paddingBottom", value: "12px" },
  "chai-pb-14": { type: "paddingBottom", value: "14px" },
  "chai-pb-16": { type: "paddingBottom", value: "16px" },
  "chai-pb-20": { type: "paddingBottom", value: "20px" },
  "chai-pb-24": { type: "paddingBottom", value: "24px" },
  "chai-pb-32": { type: "paddingBottom", value: "32px" },
  "chai-pl-0": { type: "paddingLeft", value: "0px" },
  "chai-pl-2": { type: "paddingLeft", value: "2px" },
  "chai-pl-4": { type: "paddingLeft", value: "4px" },
  "chai-pl-6": { type: "paddingLeft", value: "6px" },
  "chai-pl-8": { type: "paddingLeft", value: "8px" },
  "chai-pl-10": { type: "paddingLeft", value: "10px" },
  "chai-pl-12": { type: "paddingLeft", value: "12px" },
  "chai-pl-14": { type: "paddingLeft", value: "14px" },
  "chai-pl-16": { type: "paddingLeft", value: "16px" },
  "chai-pl-20": { type: "paddingLeft", value: "20px" },
  "chai-pl-24": { type: "paddingLeft", value: "24px" },
  "chai-pl-32": { type: "paddingLeft", value: "32px" },

  // MARGIN
  "chai-m-0": { type: "margin", value: "0px" },
  "chai-m-2": { type: "margin", value: "2px" },
  "chai-m-4": { type: "margin", value: "4px" },
  "chai-m-6": { type: "margin", value: "6px" },
  "chai-m-8": { type: "margin", value: "8px" },
  "chai-m-10": { type: "margin", value: "10px" },
  "chai-m-12": { type: "margin", value: "12px" },
  "chai-m-16": { type: "margin", value: "16px" },
  "chai-m-20": { type: "margin", value: "20px" },
  "chai-m-24": { type: "margin", value: "24px" },
  "chai-m-32": { type: "margin", value: "32px" },
  "chai-m-auto": { type: "margin", value: "auto" },
  "chai-mx-auto": { type: "marginInline", value: "auto" },
  "chai-my-auto": { type: "marginBlock", value: "auto" },
  "chai-ml-auto": { type: "marginLeft", value: "auto" },
  "chai-mr-auto": { type: "marginRight", value: "auto" },

  // MARGIN X
  "chai-mx-0": { type: "marginInline", value: "0px" },
  "chai-mx-2": { type: "marginInline", value: "2px" },
  "chai-mx-4": { type: "marginInline", value: "4px" },
  "chai-mx-6": { type: "marginInline", value: "6px" },
  "chai-mx-8": { type: "marginInline", value: "8px" },
  "chai-mx-10": { type: "marginInline", value: "10px" },
  "chai-mx-12": { type: "marginInline", value: "12px" },
  "chai-mx-16": { type: "marginInline", value: "16px" },
  "chai-mx-20": { type: "marginInline", value: "20px" },
  "chai-mx-24": { type: "marginInline", value: "24px" },
  "chai-mx-32": { type: "marginInline", value: "32px" },

  // MARGIN Y
  "chai-my-0": { type: "marginBlock", value: "0px" },
  "chai-my-2": { type: "marginBlock", value: "2px" },
  "chai-my-4": { type: "marginBlock", value: "4px" },
  "chai-my-6": { type: "marginBlock", value: "6px" },
  "chai-my-8": { type: "marginBlock", value: "8px" },
  "chai-my-10": { type: "marginBlock", value: "10px" },
  "chai-my-12": { type: "marginBlock", value: "12px" },
  "chai-my-16": { type: "marginBlock", value: "16px" },
  "chai-my-20": { type: "marginBlock", value: "20px" },
  "chai-my-24": { type: "marginBlock", value: "24px" },
  "chai-my-32": { type: "marginBlock", value: "32px" },

  // MARGIN SIDES
  "chai-mt-0": { type: "marginTop", value: "0px" },
  "chai-mt-2": { type: "marginTop", value: "2px" },
  "chai-mt-4": { type: "marginTop", value: "4px" },
  "chai-mt-6": { type: "marginTop", value: "6px" },
  "chai-mt-8": { type: "marginTop", value: "8px" },
  "chai-mt-10": { type: "marginTop", value: "10px" },
  "chai-mt-12": { type: "marginTop", value: "12px" },
  "chai-mt-16": { type: "marginTop", value: "16px" },
  "chai-mt-20": { type: "marginTop", value: "20px" },
  "chai-mt-24": { type: "marginTop", value: "24px" },
  "chai-mt-32": { type: "marginTop", value: "32px" },
  "chai-mt-auto": { type: "marginTop", value: "auto" },
  "chai-mr-0": { type: "marginRight", value: "0px" },
  "chai-mr-2": { type: "marginRight", value: "2px" },
  "chai-mr-4": { type: "marginRight", value: "4px" },
  "chai-mr-6": { type: "marginRight", value: "6px" },
  "chai-mr-8": { type: "marginRight", value: "8px" },
  "chai-mr-10": { type: "marginRight", value: "10px" },
  "chai-mr-12": { type: "marginRight", value: "12px" },
  "chai-mr-16": { type: "marginRight", value: "16px" },
  "chai-mr-20": { type: "marginRight", value: "20px" },
  "chai-mr-24": { type: "marginRight", value: "24px" },
  "chai-mr-32": { type: "marginRight", value: "32px" },
  "chai-mb-0": { type: "marginBottom", value: "0px" },
  "chai-mb-2": { type: "marginBottom", value: "2px" },
  "chai-mb-4": { type: "marginBottom", value: "4px" },
  "chai-mb-6": { type: "marginBottom", value: "6px" },
  "chai-mb-8": { type: "marginBottom", value: "8px" },
  "chai-mb-10": { type: "marginBottom", value: "10px" },
  "chai-mb-12": { type: "marginBottom", value: "12px" },
  "chai-mb-16": { type: "marginBottom", value: "16px" },
  "chai-mb-20": { type: "marginBottom", value: "20px" },
  "chai-mb-24": { type: "marginBottom", value: "24px" },
  "chai-mb-32": { type: "marginBottom", value: "32px" },
  "chai-mb-auto": { type: "marginBottom", value: "auto" },
  "chai-ml-0": { type: "marginLeft", value: "0px" },
  "chai-ml-2": { type: "marginLeft", value: "2px" },
  "chai-ml-4": { type: "marginLeft", value: "4px" },
  "chai-ml-6": { type: "marginLeft", value: "6px" },
  "chai-ml-8": { type: "marginLeft", value: "8px" },
  "chai-ml-10": { type: "marginLeft", value: "10px" },
  "chai-ml-12": { type: "marginLeft", value: "12px" },
  "chai-ml-16": { type: "marginLeft", value: "16px" },
  "chai-ml-20": { type: "marginLeft", value: "20px" },
  "chai-ml-24": { type: "marginLeft", value: "24px" },
  "chai-ml-32": { type: "marginLeft", value: "32px" },

  // GAP
  "chai-gap-2": { type: "gap", value: "2px" },
  "chai-gap-4": { type: "gap", value: "4px" },
  "chai-gap-6": { type: "gap", value: "6px" },
  "chai-gap-8": { type: "gap", value: "8px" },
  "chai-gap-10": { type: "gap", value: "10px" },

  // OPACITY
  "chai-opacity-25": { type: "opacity", value: "0.25" },
  "chai-opacity-50": { type: "opacity", value: "0.5" },
  "chai-opacity-75": { type: "opacity", value: "0.75" },
  "chai-opacity-100": { type: "opacity", value: "1" },

  // SHADOW
  "chai-shadow-sm": { type: "boxShadow", value: "0 1px 2px rgba(0,0,0,0.1)" },
  "chai-shadow-md": { type: "boxShadow", value: "0 4px 6px rgba(0,0,0,0.1)" },
  "chai-shadow-lg": { type: "boxShadow", value: "0 10px 15px rgba(0,0,0,0.2)" },

  // TEXT TRANSFORM
  "chai-uppercase": { type: "textTransform", value: "uppercase" },
  "chai-lowercase": { type: "textTransform", value: "lowercase" },
  "chai-capitalize": { type: "textTransform", value: "capitalize" },
};

export default chaiClasses;
